server.servlet.context-path: /api

project:
  scheduling:
    enabled: ${project.cache.enabled}
    initial-delay:
      load-projects: PT5S
    fixed-delay:
      load-projects: PT6H
      evict-projects: PT6H
  cache:
    enabled: true
  github:
    scheme: https
    host: api.github.com
    project-description-file: portfolio-description.json
    username: bagnascojhoel
    app-id: 375399

logging:
  level:
    org.springframework.cache: TRACE