name: Build and Deploy back

on:
  push:
    branches: ["main"]
    paths: ["back/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "flyio"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build image
        working-directory: back
        run: ./gradlew nativeCompileDocker
     
      - name: Deploy to fly.io
        working-directory: back
        run: flyctl deploy --local-only --auto-confirm
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_SECRET }}

