name: Workflow for blog
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: ["main"]
    paths: ["blog/**"]
    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        working-directory: blog
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        working-directory: blog
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_AUTH_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        working-directory: blog
        run: vercel deploy --token=${{ secrets.VERCEL_AUTH_TOKEN }}