name: Build and Deploy blog
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: ["main"]
    paths: ["blog/**"]

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        working-directory: blog
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        working-directory: blog
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_AUTH_TOKEN }}
      
      - name: Build Project Artifacts
        working-directory: blog
        run: vercel build --prod --token=${{ secrets.VERCEL_AUTH_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        working-directory: blog
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_AUTH_TOKEN }}